<?php

/**
 * @file
 * Contains kcrhi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kcrhi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kcrhi module.
    case 'help.page.kcrhi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Data Importer') . '</p>';
      return $output;

    default:
  }
}
